<?php
/**
 * @var \Fabfuel\Prophiler\ProfilerInterface $profiler
 */
?><style>
    <?php echo file_get_contents(__DIR__ . '/css/screen.css'); ?>
</style>

<script>

    var slide = function (containerId) {

        var container = document.getElementById(containerId),
            classes = container.className.split(' '),
            newClasses = [];

        classes.forEach(function (className) {
            if (className == 'closed') {
                newClasses.push('opened');
            } else if (className == 'opened') {
                newClasses.push('closed');
            } else {
                newClasses.push(className);
            }
        });
        container.className = newClasses.join(' ');
    };

</script>
<div id="prophiler">

    <div class="toolbar">
        <h1>Prophiler Toolbar</h1>

        <nav>
            <ul>
                <li>
                    <span class="label color-2"><span class="glyphicon glyphicon-time"></span> <?php printf('%.2f ms ', $profiler->getDuration() * 1000) ?></span>
                </li>
                <li>
                    <span class="label color-1"><span class="glyphicon glyphicon-tasks"></span> <?php printf('%.3f MB', memory_get_peak_usage() / 1024 / 1024) ?></span>
                </li>
                <li>
                    <a href="#" onclick="slide('prophiler-benchmarks');"><span class="label color-5"><span class="glyphicon glyphicon-dashboard"></span> Timeline</span></a>
                </li>
                <li>
                    <a href="#" onclick="slide('prophiler-logs');"><span class="label color-5"><span class="glyphicon glyphicon-align-left"></span> Logs</span></a>
                </li>

                <?php foreach ($dataCollectors as $dataCollector): ?>
                    <li>
                        <a href="#" onclick="slide('prophiler-datacollector-<?= md5($dataCollector->getTitle()) ?>');"><span class="label color-5"><span class="glyphicon glyphicon-<?= $dataCollector->getIcon() ?>"></span> <?= $dataCollector->getTitle() ?></span></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>

    <div id="prophiler-benchmarks" class="benchmarks closed">
        <?php $this->partial('partials/benchmarks', ['profiler' => $profiler]); ?>
    </div>

    <div id="prophiler-logs" class="logs closed">
        <?php $this->partial('partials/logs', ['profiler' => $profiler]); ?>
    </div>

    <?php foreach ($dataCollectors as $dataCollector): ?>
        <?php $this->partial('partials/datacollector', ['dataCollector' => $dataCollector]); ?>
    <?php endforeach; ?>
</div>

<script>
    window.addEventListener("load", function () {
        $('json').each(function (index, el) {
            el.innerHTML = JSON.stringify(JSON.parse(el.innerHTML), null, '    ');
        });
    });
</script>
